site_name: Delivery Group Governance
site_url: https://defra.github.io/delivery-group-governance
theme: 
  name: material
  logo: img/code-white.png
  favicon: img/code-black.png
  palette:
    primary: green
  font:
    text: 'Arial'
    code: 'Roboto Mono'
repo_url: https://github.com/DEFRA/delivery-group-governance
remote_branch: gh-pages
